library(ggplot2)
library(data.table)
library(dplyr)
library(tidyverse)
options(java.parameters = "- Xmx8192m")
library(extrafont)
loadfonts(device="win")
require(moonBook)
require(webr)
library(grid)
library(lemon)
library(lawstat)
library(agricolae)
library(PMCMR)
library(PMCMRplus)
library(PerformanceAnalytics)
library(ggrepel)
options(java.parameters = "- Xmx8192m")
library(ggsci)
library(tidyr)
library("scales")
library(multcompView)
library(DescTools)
library(lawstat)
library(vegan)
library(ggpubr)
library(ggplot2)
library(data.table)
library(dplyr)
library(tidyverse)
options(java.parameters = "- Xmx8192m")
library(extrafont)
loadfonts(device="win")
require(moonBook)
require(webr)
library(grid)
library(lemon)
library(lawstat)
library(agricolae)
library(PMCMR)
library(PMCMRplus)
library(PerformanceAnalytics)
library(ggrepel)
options(java.parameters = "- Xmx8192m")
library(ggsci)
library(tidyr)
library("scales")
library(multcompView)
library(DescTools)
library(lawstat)
library(vegan)
library(ggpubr)
library(ggtext)
library(VennDiagram)
library("ggVennDiagram")
library(ggforce)
library(VIM)
library(naniar)
library(missMDA)
library(Amelia)
library(mice)
library(missForest)
library(FactoMineR)
library(mixOmics)
library(RVAideMemoire)
Sys.setlocale("LC_TIME","english")
library(openair)
library(tidyverse)
library(lubridate)
library(worldmet)
library(openairmaps)
library("scales")
library(dendextend)
library(cowplot)
library(xlsx)
library(data.table)
library(dplyr)
library(tidyverse)
library(openxlsx)
library(indicspecies)
library(labdsv)
library(ggh4x)
library(scatterplot3d)
library(openair)
library(tidyverse)
library(lubridate)
library(worldmet)
library(openairmaps)
library("scales")
library(dendextend)
library(cowplot)
library(xlsx)
library(data.table)
library(dplyr)
library(tidyverse)
library(openxlsx)
library(indicspecies)
library(labdsv)

library(data.table)
library(lemon)
library(ggforce)
require(moonBook)
require(webr)
library(grid)

library(patchwork)
library("ggpattern")


filepng <- function(filename){
  # check that ftmsObj is of the correct class #
  
  filename=paste0("Figure/",filename,"_",format(Sys.time(), "%Y_%m_%d"),".png")
  
  return(filename)
}

Sys.setlocale("LC_TIME","english")

source("Rscript/func_filename.R")
source("Rscript/func_generate_lable.R")
source("Rscript/func_upper_fence_label.R")
#source("Rscript/piedonut_ms.R")
insert_minor_1 <- function(major_labs, n_minor) {labs <- 
  c( sapply( major_labs, function(x) c(x, rep("", 4) ) ) )
labs[1:(length(labs)-n_minor)]}

insert_minor_2 <- function(major_labs, n_minor) {labs <- 
  c( sapply( major_labs, function(x) c(x, rep("", 1) ) ) )
labs[1:(length(labs)-n_minor)]}

